name: Makefile CI

on:
  push:

    paths:
 
      - scripts/**
      - .github/workflows/**
      
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    

    steps:
    - uses: |
        actions/checkout@v2
        docker://pandoc/core:2.9
        with:
          args: "--help" # gets appended to pandoc command
    
    - name: Run apt update
      run: sudo apt update  
    
    - name: Build pages
      run: make -f ./scripts/make.make caves

    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
