name: Makefile CI

on:
  push:

    paths:
 
      - scripts/**
      - .github/workflows/**
      
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Run apt update
      run: sudo apt update
      
    - name: Install Pandoc
      run: |
        wget https://hackage.haskell.org/package/pandoc-1.17.0.3/pandoc-1.17.0.3.tar.gz
        tar xvzf pandoc-1.17.0.3.tar.gz
        cd pandoc-1.17.0.3  
    
    - name: Build pages
      run: make -f ./scripts/make.make caves

    - name: Run check
      run: make check
      
    - name: Run distcheck
      run: make distcheck
